name: Release Infrastructure

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: "AWS_ACCESS_KEY_ID from AWS Academy lab"
        required: true
        type: string
      aws_secret_access_key:
        description: "AWS_SECRET_ACCESS_KEY from AWS Academy lab"
        required: true
        type: string
      aws_session_token:
        description: "AWS_SESSION_TOKEN from AWS Academy lab"
        required: true
        type: string
      aws_region:
        description: "AWS Region (e.g., us-west-2)"
        required: true
        type: string
        default: "us-west-2"

jobs:
  terraform-release:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: iac   # All terraform commands run in /iac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
          aws-session-token: ${{ inputs.aws_session_token }}
          aws-region: ${{ inputs.aws_region }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply --auto-approve tfplan

      - name: Verify deployment (Terraform Show)
        run: terraform show
