name: Terraform Release

on:
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: 'Temporary AWS Access Key'
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        description: 'Temporary AWS Secret Key'
        required: true
        type: string
      AWS_SESSION_TOKEN:
        description: 'Temporary AWS Session Token'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: iac  # Folder where your .tf files live

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=${{ inputs.AWS_SESSION_TOKEN }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve
